package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private short codactividad;
     private String desc1;
     private Set<Rolatividad> rolatividads = new HashSet<Rolatividad>(0);

    public Actividad() {
    }

	
    public Actividad(short codactividad, String desc1) {
        this.codactividad = codactividad;
        this.desc1 = desc1;
    }
    public Actividad(short codactividad, String desc1, Set<Rolatividad> rolatividads) {
       this.codactividad = codactividad;
       this.desc1 = desc1;
       this.rolatividads = rolatividads;
    }
   
    public short getCodactividad() {
        return this.codactividad;
    }
    
    public void setCodactividad(short codactividad) {
        this.codactividad = codactividad;
    }
    public String getDesc1() {
        return this.desc1;
    }
    
    public void setDesc1(String desc1) {
        this.desc1 = desc1;
    }
    public Set<Rolatividad> getRolatividads() {
        return this.rolatividads;
    }
    
    public void setRolatividads(Set<Rolatividad> rolatividads) {
        this.rolatividads = rolatividads;
    }




}


