package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Correos generated by hbm2java
 */
public class Correos  implements java.io.Serializable {


     private BigDecimal idcorreo;
     private Persona persona;
     private String correo;

    public Correos() {
    }

    public Correos(BigDecimal idcorreo, Persona persona, String correo) {
       this.idcorreo = idcorreo;
       this.persona = persona;
       this.correo = correo;
    }
   
    public BigDecimal getIdcorreo() {
        return this.idcorreo;
    }
    
    public void setIdcorreo(BigDecimal idcorreo) {
        this.idcorreo = idcorreo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


