package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private short idestado;
     private String nombre;
     private String desc1;
     private Set<Scambio> scambios = new HashSet<Scambio>(0);

    public Estados() {
    }

	
    public Estados(short idestado, String nombre, String desc1) {
        this.idestado = idestado;
        this.nombre = nombre;
        this.desc1 = desc1;
    }
    public Estados(short idestado, String nombre, String desc1, Set<Scambio> scambios) {
       this.idestado = idestado;
       this.nombre = nombre;
       this.desc1 = desc1;
       this.scambios = scambios;
    }
   
    public short getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(short idestado) {
        this.idestado = idestado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDesc1() {
        return this.desc1;
    }
    
    public void setDesc1(String desc1) {
        this.desc1 = desc1;
    }
    public Set<Scambio> getScambios() {
        return this.scambios;
    }
    
    public void setScambios(Set<Scambio> scambios) {
        this.scambios = scambios;
    }




}


