package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Files generated by hbm2java
 */
public class Files  implements java.io.Serializable {


     private BigDecimal idfile;
     private Scambio scambio;
     private String filename;
     private String filepath;
     private Date fechacreacion;

    public Files() {
    }

    public Files(BigDecimal idfile, Scambio scambio, String filename, String filepath, Date fechacreacion) {
       this.idfile = idfile;
       this.scambio = scambio;
       this.filename = filename;
       this.filepath = filepath;
       this.fechacreacion = fechacreacion;
    }
   
    public BigDecimal getIdfile() {
        return this.idfile;
    }
    
    public void setIdfile(BigDecimal idfile) {
        this.idfile = idfile;
    }
    public Scambio getScambio() {
        return this.scambio;
    }
    
    public void setScambio(Scambio scambio) {
        this.scambio = scambio;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


