package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GrupousuarioId generated by hbm2java
 */
public class GrupousuarioId  implements java.io.Serializable {


     private BigDecimal idusu;
     private BigDecimal idgrupo;

    public GrupousuarioId() {
    }

    public GrupousuarioId(BigDecimal idusu, BigDecimal idgrupo) {
       this.idusu = idusu;
       this.idgrupo = idgrupo;
    }
   
    public BigDecimal getIdusu() {
        return this.idusu;
    }
    
    public void setIdusu(BigDecimal idusu) {
        this.idusu = idusu;
    }
    public BigDecimal getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(BigDecimal idgrupo) {
        this.idgrupo = idgrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupousuarioId) ) return false;
		 GrupousuarioId castOther = ( GrupousuarioId ) other; 
         
		 return ( (this.getIdusu()==castOther.getIdusu()) || ( this.getIdusu()!=null && castOther.getIdusu()!=null && this.getIdusu().equals(castOther.getIdusu()) ) )
 && ( (this.getIdgrupo()==castOther.getIdgrupo()) || ( this.getIdgrupo()!=null && castOther.getIdgrupo()!=null && this.getIdgrupo().equals(castOther.getIdgrupo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdusu() == null ? 0 : this.getIdusu().hashCode() );
         result = 37 * result + ( getIdgrupo() == null ? 0 : this.getIdgrupo().hashCode() );
         return result;
   }   


}


