package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private BigDecimal idgrupo;
     private String area;
     private Date fechacreacion;
     private Date fechacierre;
     private Set<Grupousuario> grupousuarios = new HashSet<Grupousuario>(0);

    public Grupo() {
    }

	
    public Grupo(BigDecimal idgrupo, String area, Date fechacreacion) {
        this.idgrupo = idgrupo;
        this.area = area;
        this.fechacreacion = fechacreacion;
    }
    public Grupo(BigDecimal idgrupo, String area, Date fechacreacion, Date fechacierre, Set<Grupousuario> grupousuarios) {
       this.idgrupo = idgrupo;
       this.area = area;
       this.fechacreacion = fechacreacion;
       this.fechacierre = fechacierre;
       this.grupousuarios = grupousuarios;
    }
   
    public BigDecimal getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(BigDecimal idgrupo) {
        this.idgrupo = idgrupo;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechacierre() {
        return this.fechacierre;
    }
    
    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }
    public Set<Grupousuario> getGrupousuarios() {
        return this.grupousuarios;
    }
    
    public void setGrupousuarios(Set<Grupousuario> grupousuarios) {
        this.grupousuarios = grupousuarios;
    }




}


