package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private BigDecimal codrol;
     private String desc1;
     private Set<Usuariorol> usuariorols = new HashSet<Usuariorol>(0);
     private Set<Rolatividad> rolatividads = new HashSet<Rolatividad>(0);

    public Rol() {
    }

	
    public Rol(BigDecimal codrol, String desc1) {
        this.codrol = codrol;
        this.desc1 = desc1;
    }
    public Rol(BigDecimal codrol, String desc1, Set<Usuariorol> usuariorols, Set<Rolatividad> rolatividads) {
       this.codrol = codrol;
       this.desc1 = desc1;
       this.usuariorols = usuariorols;
       this.rolatividads = rolatividads;
    }
   
    public BigDecimal getCodrol() {
        return this.codrol;
    }
    
    public void setCodrol(BigDecimal codrol) {
        this.codrol = codrol;
    }
    public String getDesc1() {
        return this.desc1;
    }
    
    public void setDesc1(String desc1) {
        this.desc1 = desc1;
    }
    public Set<Usuariorol> getUsuariorols() {
        return this.usuariorols;
    }
    
    public void setUsuariorols(Set<Usuariorol> usuariorols) {
        this.usuariorols = usuariorols;
    }
    public Set<Rolatividad> getRolatividads() {
        return this.rolatividads;
    }
    
    public void setRolatividads(Set<Rolatividad> rolatividads) {
        this.rolatividads = rolatividads;
    }




}


