package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1



/**
 * Rolatividad generated by hbm2java
 */
public class Rolatividad  implements java.io.Serializable {


     private RolatividadId id;
     private Actividad actividad;
     private Rol rol;

    public Rolatividad() {
    }

    public Rolatividad(RolatividadId id, Actividad actividad, Rol rol) {
       this.id = id;
       this.actividad = actividad;
       this.rol = rol;
    }
   
    public RolatividadId getId() {
        return this.id;
    }
    
    public void setId(RolatividadId id) {
        this.id = id;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


