package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RolatividadId generated by hbm2java
 */
public class RolatividadId  implements java.io.Serializable {


     private BigDecimal codrol;
     private short codactividad;

    public RolatividadId() {
    }

    public RolatividadId(BigDecimal codrol, short codactividad) {
       this.codrol = codrol;
       this.codactividad = codactividad;
    }
   
    public BigDecimal getCodrol() {
        return this.codrol;
    }
    
    public void setCodrol(BigDecimal codrol) {
        this.codrol = codrol;
    }
    public short getCodactividad() {
        return this.codactividad;
    }
    
    public void setCodactividad(short codactividad) {
        this.codactividad = codactividad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolatividadId) ) return false;
		 RolatividadId castOther = ( RolatividadId ) other; 
         
		 return ( (this.getCodrol()==castOther.getCodrol()) || ( this.getCodrol()!=null && castOther.getCodrol()!=null && this.getCodrol().equals(castOther.getCodrol()) ) )
 && (this.getCodactividad()==castOther.getCodactividad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodrol() == null ? 0 : this.getCodrol().hashCode() );
         result = 37 * result + this.getCodactividad();
         return result;
   }   


}


