package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Scambio generated by hbm2java
 */
public class Scambio  implements java.io.Serializable {


     private BigDecimal idsolicitud;
     private Estados estados;
     private Usuarios usuarios;
     private String titulo;
     private String shortdesc;
     private Date fechaapertura;
     private Date fechacierre;
     private String longdesc;
     private Set<Files> fileses = new HashSet<Files>(0);
     private Set<Revisiones> revisioneses = new HashSet<Revisiones>(0);

    public Scambio() {
    }

	
    public Scambio(BigDecimal idsolicitud, Estados estados, Usuarios usuarios, String titulo, String shortdesc, Date fechaapertura) {
        this.idsolicitud = idsolicitud;
        this.estados = estados;
        this.usuarios = usuarios;
        this.titulo = titulo;
        this.shortdesc = shortdesc;
        this.fechaapertura = fechaapertura;
    }
    public Scambio(BigDecimal idsolicitud, Estados estados, Usuarios usuarios, String titulo, String shortdesc, Date fechaapertura, Date fechacierre, String longdesc, Set<Files> fileses, Set<Revisiones> revisioneses) {
       this.idsolicitud = idsolicitud;
       this.estados = estados;
       this.usuarios = usuarios;
       this.titulo = titulo;
       this.shortdesc = shortdesc;
       this.fechaapertura = fechaapertura;
       this.fechacierre = fechacierre;
       this.longdesc = longdesc;
       this.fileses = fileses;
       this.revisioneses = revisioneses;
    }
   
    public BigDecimal getIdsolicitud() {
        return this.idsolicitud;
    }
    
    public void setIdsolicitud(BigDecimal idsolicitud) {
        this.idsolicitud = idsolicitud;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getShortdesc() {
        return this.shortdesc;
    }
    
    public void setShortdesc(String shortdesc) {
        this.shortdesc = shortdesc;
    }
    public Date getFechaapertura() {
        return this.fechaapertura;
    }
    
    public void setFechaapertura(Date fechaapertura) {
        this.fechaapertura = fechaapertura;
    }
    public Date getFechacierre() {
        return this.fechacierre;
    }
    
    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }
    public String getLongdesc() {
        return this.longdesc;
    }
    
    public void setLongdesc(String longdesc) {
        this.longdesc = longdesc;
    }
    public Set<Files> getFileses() {
        return this.fileses;
    }
    
    public void setFileses(Set<Files> fileses) {
        this.fileses = fileses;
    }
    public Set<Revisiones> getRevisioneses() {
        return this.revisioneses;
    }
    
    public void setRevisioneses(Set<Revisiones> revisioneses) {
        this.revisioneses = revisioneses;
    }




}


