package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private BigDecimal idphone;
     private Persona persona;
     private String numero;

    public Telefonos() {
    }

    public Telefonos(BigDecimal idphone, Persona persona, String numero) {
       this.idphone = idphone;
       this.persona = persona;
       this.numero = numero;
    }
   
    public BigDecimal getIdphone() {
        return this.idphone;
    }
    
    public void setIdphone(BigDecimal idphone) {
        this.idphone = idphone;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


