package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1



/**
 * Usuariorol generated by hbm2java
 */
public class Usuariorol  implements java.io.Serializable {


     private UsuariorolId id;
     private Rol rol;
     private Usuarios usuarios;

    public Usuariorol() {
    }

    public Usuariorol(UsuariorolId id, Rol rol, Usuarios usuarios) {
       this.id = id;
       this.rol = rol;
       this.usuarios = usuarios;
    }
   
    public UsuariorolId getId() {
        return this.id;
    }
    
    public void setId(UsuariorolId id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


