package entity;
// Generated 07-jul-2015 11:43:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private BigDecimal idusu;
     private Persona persona;
     private String nusuario;
     private String pass;
     private Date lta;
     private Set<Scambio> scambios = new HashSet<Scambio>(0);
     private Set<Usuariorol> usuariorols = new HashSet<Usuariorol>(0);
     private Set<Grupousuario> grupousuarios = new HashSet<Grupousuario>(0);

    public Usuarios() {
    }

	
    public Usuarios(BigDecimal idusu, Persona persona, String nusuario, String pass, Date lta) {
        this.idusu = idusu;
        this.persona = persona;
        this.nusuario = nusuario;
        this.pass = pass;
        this.lta = lta;
    }
    public Usuarios(BigDecimal idusu, Persona persona, String nusuario, String pass, Date lta, Set<Scambio> scambios, Set<Usuariorol> usuariorols, Set<Grupousuario> grupousuarios) {
       this.idusu = idusu;
       this.persona = persona;
       this.nusuario = nusuario;
       this.pass = pass;
       this.lta = lta;
       this.scambios = scambios;
       this.usuariorols = usuariorols;
       this.grupousuarios = grupousuarios;
    }
   
    public BigDecimal getIdusu() {
        return this.idusu;
    }
    
    public void setIdusu(BigDecimal idusu) {
        this.idusu = idusu;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNusuario() {
        return this.nusuario;
    }
    
    public void setNusuario(String nusuario) {
        this.nusuario = nusuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Date getLta() {
        return this.lta;
    }
    
    public void setLta(Date lta) {
        this.lta = lta;
    }
    public Set<Scambio> getScambios() {
        return this.scambios;
    }
    
    public void setScambios(Set<Scambio> scambios) {
        this.scambios = scambios;
    }
    public Set<Usuariorol> getUsuariorols() {
        return this.usuariorols;
    }
    
    public void setUsuariorols(Set<Usuariorol> usuariorols) {
        this.usuariorols = usuariorols;
    }
    public Set<Grupousuario> getGrupousuarios() {
        return this.grupousuarios;
    }
    
    public void setGrupousuarios(Set<Grupousuario> grupousuarios) {
        this.grupousuarios = grupousuarios;
    }




}


